# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-05 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yoins', '0002_auto_20160205_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='products_image_4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_5',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_6',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_7',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_8',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price1_qty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price2_qty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price3_qty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price4_qty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price5',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price5_qty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price6',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price6_qty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price7',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price7_qty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price8',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_price8_qty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_qty_blocks',
        ),
    ]
