# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-05 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yoins', '0003_auto_20160205_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='products_au_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_cost_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_de_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_10',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_11',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_12',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_image_9',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_uk_low_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_uk_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_usa_low_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_usa_price',
        ),
    ]
