# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-06 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yoins', '0006_auto_20160206_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': True},
        ),
    ]
