# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-02-06 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoins', '0007_auto_20160206_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='access',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_group',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='modi_time',
            field=models.IntegerField(null=True),
        ),
    ]
